sudo: required

language: node_js
node_js:
  - "node"
  - "8"

addons:
  chrome: stable

env:
  - CATE_TESTING=1

cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email: false
